// generated by vite.config.js -- do not edit
const V = 'allex-20260726031108';

self.addEventListener('install', (e) => {
  self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) {
      if (k !== V) await caches.delete(k);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  // Only same-origin GETs. Never touch the recording endpoint or anything cross
  // origin; a cached POST or opaque response would be worse than no cache.
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // index.html must stay network-first, or a deploy would never be picked up:
  // it is the one file whose name does not change between builds.
  const isDoc = req.mode === 'navigate' || url.pathname.endsWith('.html');

  e.respondWith((async () => {
    const cache = await caches.open(V);
    if (isDoc) {
      try {
        const fresh = await fetch(req);
        cache.put(req, fresh.clone());
        return fresh;
      } catch (err) {
        return (await cache.match(req)) || Response.error();
      }
    }
    const hit = await cache.match(req);
    if (hit) return hit;
    // Revalidate when POPULATING a fresh cache. A plain fetch() here goes through
    // the HTTP cache, and GitHub Pages sends max-age=600 with nothing
    // configurable -- so a new service worker version would happily fill its new
    // cache with the PREVIOUS deploy's files and then serve them forever. That is
    // not hypothetical: a verified-good deploy still handed this browser the old
    // model, and the stale copy would have outlived the bug it was meant to fix.
    // 'no-cache' revalidates rather than re-downloads, so an unchanged asset costs
    // a 304 and this happens once per deploy, not per visit.
    const res = await fetch(req, { cache: 'no-cache' });
    if (res.ok) cache.put(req, res.clone());
    return res;
  })());
});
